### ISSUE TITLE
Issues after combing through time_profiles.py after merge.

### ISSUE THREAD

**Issue by thejevans** [thejevans/mla#14]
@jasonfan1997:
- I can't remember where we landed about effective exposure. Can you explain here why it's necessary for ThreeML?
- Docstrings for effective exposure need to be completed, if they're being kept.

**Comment by jasonfan1997** [comment]
It is needed for the consistency of the unit. I would strongly disfavor having a separate unit system in 3ML as the confusion can be huge if we are fitting different experiments at the same time.

**Comment by thejevans** [comment]
As @mjlarson said last time we talked, it makes more sense to IceCubers to not have to faff about with time dependent flux normalizations, so we'll likely hit less resistance from the collaboration if our base software uses the time integrated flux instead. As long as these are simply functions for converting later, that's fine, but we should make the default behavior time integrated.

**Comment by jasonfan1997** [comment]
I have to insist on this one. It is related to how 3ML defines a model. For TimeDependentPsAnalysis, it uses time-integrated flux instead of effective exposure and I think it should be(and it is the current way). But for 3ML however, it is necessary to keep effective exposure and convert to time-integrated flux(aka the other way around).

**Comment by thejevans** [comment]
yeah that's fine, I just wanted to make sure that `TimeDependentPsAnalysis` worked the way that it does.
