### ISSUE TITLE
Uniform Time Profile has bad parameters

### ISSUE THREAD

**Issue by thejevans** [thejevans/mla#9]
The uniform time profile has bad fitting parameters. It currently uses start and end, but this can result in end crossing over start in fitting, or at least wanting to. It's better to use start and length, where length is bounded by 0 on the left.

**Comment by jasonfan1997** [comment]
I will change that. Also I will want to point out that the current TimeDependentPsAnalysis doesn't fit the time profile but just use the fix time profile to evaluate the likelihood. I still haven't figure out a way to better fit the time profile so I will put it on hold for now.

**Comment by mjlarson** [comment]
There's not a great way to fit some of the possible profiles. The uniform time profile in particular will have a non-smooth likelihood space due to the hard edges in the PDF. You may be able to get away with a standard minimizer with other PDFs, but a uniform distribution may require a brute force scan instead.

**Comment by thejevans** [comment]
would this problem also extend to the histogram one?

**Comment by jasonfan1997** [comment]
I think you can only fit an off-set to a histogram pdf? So probably ok?

**Comment by thejevans** [comment]
@mjlarson how were the box profiles fit for txs?

**Comment by thejevans** [comment]
fixed.
